name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# SAME
#on:
#  push:
#    branches:
#      - master
#      - fix/**
#      - feat/**

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: install chromium-browser
        run: sudo apt-get install chromium-browser
      - name: get package destination
        run: dpkg -L chromium-browser
      - name: test:ci
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:ci # will run `yarn test` command
